spring:
  application:
    name: tech.blog
  profiles:
    default: local
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
