spring:
  application:
    name: tech.blog
  profiles:
    default: local
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  user-events:
    enabled: false
    queue-url: ""
    region: us-east-1
    wait-time-seconds: 20
    max-messages: 10
    poll-delay-ms: 1000
